services:
  workout_app:
    build: .
    container_name: workout_app
    env_file:
      - .env
    ports:
      # If PORT is not set in .env, default to 8000 on the host
      - "${PORT:-5000}:5000"
    restart: unless-stopped
    volumes:
      - ./data:/app/workout_log
    environment:
      # Default to UTC if not set
      - TZ=${TZ:-UTC}